const icons={sale:'<rect x="3" y="5" width="18" height="15" rx="2"/><path d="M3 10h18M8 5V3m8 2V3m-9 12h4"/>',stock:'<path d="m12 3 9 5-9 5-9-5 9-5Zm-9 5v9l9 5 9-5V8M12 13v9"/>',assemble:'<path d="m4 7 8-4 8 4-8 4-8-4Zm0 5 8 4 8-4M4 17l8 4 8-4"/>',history:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',buy:'<path d="M8 3h8v4H8zM8 5H5v16h14V5h-3M8 12h8m-8 4h5"/>',check:'<path d="m5 12 4 4L19 6"/>'};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[n]||icons.stock}</svg>`;
const navs=[['vente','sale','Vente express','Vendre'],['stock','stock','Stock disponible','Stock'],['preparation','assemble','Préparer des kits','Préparer'],['achats','buy','Réapprovisionnement','Achats'],['historique','history','Historique','Historique']];
for(const id of ['desktop-nav','mobile-nav'])document.getElementById(id).innerHTML=navs.map(([view,i,label,short])=>`<button data-view="${view}" class="${view==='vente'?'active':''}">${icon(i)}${id==='mobile-nav'?short:label}</button>`).join('');
document.getElementById('today').textContent=new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'long',year:'numeric',timeZone:'Africa/Conakry'}).format(new Date());
import {articles,kits,kitById,articleById,capacity,requirements} from './data.mjs';
const $=s=>document.querySelector(s), money=n=>new Intl.NumberFormat('fr-FR').format(n), today=()=>new Date().toISOString().slice(0,10);
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
import {createClient} from './supabase.js';
import {createHhtBackend} from './backend.mjs';
const supabase=createClient('https://hvhkiodvkdcauoivtidi.supabase.co','sb_publishable_VnhGhJPN0PEUXYIHEn7vyw_uTSKcvLk');
const backend=createHhtBackend(supabase);
const emptyState=()=>({raw:{},ready:{},events:[]});
let state=emptyState(),profile=null,serverTotals={quantity:0,amount:0},storageError=false,view='vente',role='commercial',filter='Tous',selected=null,qty=1,saleDate=today(),saleToken='',busy=false,lastSale=null,stockTab='kits',stockSearch='',prepKit='cp',prepQty=1,plan={},packing={},toastTimer,pollTimer,refreshBusy=false,hasOlder=false;
const dialog=$('#dialog');
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
function canceled(id){return state.events.some(e=>e.id===id&&e.cancelled||e.type==='cancel'&&e.saleId===id);}
function saleTotals(){return {qty:serverTotals.quantity,amount:serverTotals.amount};}
function heading(eyebrow,title,subtitle,extra=''){return `<div class="page-heading"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p>${subtitle}</p></div>${extra}</div>`;}
function renderNav(){const visible=role==='depot'?navs:navs.filter(n=>['vente','stock','historique'].includes(n[0]));for(const id of ['desktop-nav','mobile-nav'])$('#'+id).innerHTML=visible.map(([v,i,label,short])=>`<button data-view="${v}" class="${view===v?'active':''}" ${view===v?'aria-current="page"':''}>${icon(i)}${id==='mobile-nav'?short:label}</button>`).join('');$('#breadcrumb').textContent=navs.find(n=>n[0]===view)[2];}
function render(){if(!profile)return;renderNav();$('#main').innerHTML=({vente:renderSales,stock:renderStock,preparation:renderPrep,achats:renderBuy,historique:renderHistory})[view]();renderStatus();}
function kitCard(k){const n=state.ready[k.id];return `<button class="kit-card ${selected===k.id?'selected':''}" data-kit="${k.id}" ${n===0||!k.active?'disabled':''} aria-label="Vendre ${k.name}, ${money(k.price)} GNF, ${n} disponibles"><span class="kit-level ${k.group==='Secondaire'?'secondary':''}">${k.level}</span><span class="choose" aria-hidden="true">${selected===k.id?'✓':'+'}</span><h3>${k.short}</h3><span>${k.variant}</span><strong class="price">${money(k.price)} <small>GNF</small></strong><span class="availability ${n===0?'out':n<5?'low':''}">${n===0?'Aucun kit prêt':`${n} prêt${n>1?'s':''} à vendre`}</span></button>`;}
function renderSales(){const t=saleTotals();return heading('COMPTOIR HHT','Une vente, et c’est fait.','Choisissez un kit. Le prix et la date sont déjà prêts.','<span class="pill">8 références · 2026–2027</span>')+`<div class="stats"><article><span>Kits prêts à vendre</span><strong>${Object.values(state.ready).reduce((a,b)=>a+b,0)} <small>kits</small></strong></article><article><span>Ventes du jour</span><strong>${t.qty} <small>kits</small></strong></article><article><span>Montant du jour</span><strong>${money(t.amount)} <small>GNF</small></strong></article></div><div class="sale-layout"><div><section class="panel"><div class="panel-heading"><h2>Quel kit souhaitez-vous vendre ?</h2><small>Prix par kit</small></div><div class="filters" aria-label="Filtrer les niveaux">${['Tous','Maternelle','Primaire','Secondaire'].map(f=>`<button class="filter ${filter===f?'active':''}" data-filter="${f}" aria-pressed="${filter===f}">${f}</button>`).join('')}</div><div class="kit-grid">${kits.filter(k=>filter==='Tous'||k.group===filter).map(kitCard).join('')}</div></section><section class="panel recent"><div class="panel-heading"><h2>Dernières ventes</h2><button class="text-btn" data-view="historique">Tout voir</button></div>${salesList(3)}</section></div><aside class="panel receipt" aria-label="Récapitulatif de la vente"><div class="receipt-inner">${receipt()}</div></aside></div>`;}
function receipt(){if(lastSale)return `<div class="success"><div class="success-mark">✓</div><h2 id="dialog-title">Vente enregistrée</h2><p>${lastSale.qty} × ${kitById(lastSale.kitId).name}</p><strong class="price">${money(lastSale.amount)} <small>GNF</small></strong><p class="small">${state.ready[lastSale.kitId]} kit(s) encore prêts à vendre.</p><button class="primary full" data-action="new-sale">Nouvelle vente</button><button class="text-btn" data-action="cancel-sale" data-id="${lastSale.id}">Annuler cette vente</button></div>`;
const k=kitById(selected);if(!k)return `<div class="receipt-top">${icon('sale')}<h2>Votre vente</h2></div><div class="empty-cart"><span class="empty-symbol">${icon('sale')}</span><strong>Prêt pour la prochaine vente</strong>Touchez un kit pour commencer.</div><p class="receipt-note">Aucun nom de parent à saisir.<br>La quantité est réglée sur 1.</p>`;
return `<div class="receipt-top">${icon('sale')}<h2 id="dialog-title">Votre vente</h2><button class="close mobile-only" data-action="close" aria-label="Fermer">×</button></div><h3>${k.name}</h3><p class="small muted">${money(k.price)} GNF / kit · ${state.ready[k.id]} disponibles</p><label for="sale-qty" class="small">Quantité vendue</label><div class="qty"><button data-action="minus" aria-label="Diminuer la quantité" ${qty<=1?'disabled':''}>−</button><input id="sale-qty" type="number" inputmode="numeric" min="1" max="${state.ready[k.id]}" value="${qty}" aria-label="Quantité vendue"><button data-action="plus" aria-label="Augmenter la quantité" ${qty>=state.ready[k.id]?'disabled':''}>+</button></div><details><summary>Date : ${new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium',timeZone:'UTC'}).format(new Date(saleDate+'T12:00:00Z'))}</summary><label class="field">Date de vente<input id="sale-date" type="date" max="${today()}" value="${saleDate}"></label></details><div class="total"><span>Total</span><strong id="sale-total">${money(k.price*qty)} <small>GNF</small></strong></div><p class="error" id="sale-error" role="alert"></p><button class="primary full" data-action="sell" ${busy||storageError?'disabled':''}>${icon('check')} Enregistrer la vente</button><p class="receipt-note">Le stock de kits est mis à jour dès la validation.</p>`;}
function salesList(limit=100){const sales=state.events.filter(e=>e.type==='sale').slice(0,limit);return sales.length?sales.map(e=>`<div class="history-row"><div><strong>${e.qty} × ${kitById(e.kitId).name}</strong><small>${formatDate(e.at)} · ${canceled(e.id)?'Annulée':escape(e.author)}</small></div><div class="amount"><strong>${money(e.amount)} GNF</strong>${canceled(e.id)?'<small>Stock rétabli</small>':`<button class="text-btn" data-action="cancel-sale" data-id="${e.id}">Annuler</button>`}</div></div>`).join(''):'<div class="empty-row">Aucune vente pour le moment.<br>La première apparaîtra ici.</div>';}
function formatDate(at){return new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Africa/Conakry'}).format(new Date(at));}
function showDialog(content){dialog.innerHTML=content;if(!dialog.open)dialog.showModal();}
function updateReceipt(){const aside=$('.receipt-inner');if(aside)aside.innerHTML=receipt();if(dialog.open&&dialog.dataset.kind==='sale')dialog.innerHTML=receipt();}
function selectKit(id){if(!kitById(id)?.active||state.ready[id]<1)throw Error('Ce kit n’est pas disponible.');selected=id;qty=1;saleDate=today();saleToken=crypto.randomUUID();lastSale=null;render();if(matchMedia('(max-width:600px)').matches){dialog.dataset.kind='sale';showDialog(receipt());}else $('.receipt').scrollIntoView({block:'nearest',behavior:'smooth'});}
function eventFrom(row){return {...row,kitId:row.kit_id,articleId:row.article_id,qty:row.quantity,amount:row.amount_gnf,at:row.created_at,date:row.sale_date,author:row.actor_name,saleId:row.cancelled_sale_id};}
function applySnapshot(s){
 profile=s.profile;role=['admin','depot'].includes(profile.role)?'depot':'commercial';
 serverTotals=s.today;state.raw=Object.fromEntries(s.articles.map(a=>[a.id,a.stock]));state.ready=Object.fromEntries(s.kits.map(k=>[k.id,k.ready]));
 for(const a of s.articles){const target=articleById(a.id);if(target)Object.assign(target,{threshold:a.threshold,stock:a.stock});}
 for(const k of s.kits){const target=kitById(k.id);if(target)Object.assign(target,{price:k.price,recipe:k.recipe,ready:k.ready,active:k.active});}
 $('#profile-label').textContent=profile.name+' · '+({admin:'Administrateur',depot:'Dépôt',commercial:'Commercial'}[profile.role]);
 document.body.classList.remove('signed-out');storageError=false;
}
function pendingKey(){return 'hht-pending-'+profile.id;}
function readPending(){return JSON.parse(localStorage.getItem(pendingKey())||'null');}
function renderStatus(){
 if(!profile)return;const el=$('#sync-status');let pending;
 try{pending=readPending();}catch{storageError=true;}
 el.classList.toggle('warning',storageError||!!pending);
 if(pending)el.innerHTML='Un mouvement attend sa confirmation. <button class="text-btn" data-action="retry">Vérifier / réessayer</button>';
 else el.textContent=storageError?'Connexion à vérifier. Les chiffres affichés peuvent avoir changé. Réessayez avant de vendre.':'Stock partagé · actualisation automatique';
}
async function refreshData(){
 const [snapshot,history]=await Promise.all([backend.snapshot(),backend.history()]);
 applySnapshot(snapshot);
 const incoming=history.map(eventFrom),seen=new Set(incoming.map(e=>e.id));
 state.events=[...incoming,...state.events.filter(e=>!seen.has(e.id))].sort((a,b)=>b.sequence-a.sequence);
 if(state.events.length===incoming.length)hasOlder=history.length===100;
 renderStatus();
}
async function commit(action){
 if(!profile)throw Error('Connectez-vous pour enregistrer un mouvement.');
 const {id,...payload}=action;
 const run=async()=>{
  let pending;
  try{pending=readPending();}catch{throw Error('Le stockage de cet appareil est indisponible. Activez-le pour sécuriser les enregistrements.');}
  if(pending&&JSON.stringify(pending.action)!==JSON.stringify(payload))throw Error('Vérifiez le mouvement en attente avec le bouton en haut de la page avant de continuer.');
  const request=pending||{id,action:payload};
  try{localStorage.setItem(pendingKey(),JSON.stringify(request));}catch{throw Error('Impossible de sécuriser cet enregistrement sur votre appareil.');}
  renderStatus();let row;
  try{row=await backend.move(request.id,request.action);}catch(error){
   // SQL/PostgREST errors confirm a rejected transaction; transport errors may follow a committed write.
   if(/^[A-Z0-9]{5}$/.test(error.code||'')||/^PGRST/.test(error.code||''))localStorage.removeItem(pendingKey());
   renderStatus();throw Error(error.code?error.message:'Connexion interrompue. Vérifiez le mouvement en attente avant toute nouvelle saisie.');
  }
  localStorage.removeItem(pendingKey());
  const event=eventFrom(row);
  try{await refreshData();}catch{
   // A successful write stays successful even if refreshing the display fails.
   if(!state.events.some(e=>e.id===event.id)){
    state.events.unshift(event);
    if(row.kit_id)state.ready[row.kit_id]=(state.ready[row.kit_id]||0)+row.ready_change;
    for(const [key,delta] of Object.entries(row.raw_changes||{}))state.raw[key]=(state.raw[key]||0)+delta;
   }
   storageError=true;renderStatus();
  }
  return event;
 };
 return navigator.locks?navigator.locks.request(pendingKey(),run):run();
}
function showLogin(message=''){
 document.body.classList.add('signed-out');$('#print-area').innerHTML='';
 $('#main').innerHTML=`<section class="panel login-panel"><img src="kolilink-logo.png" alt="Kolilink"><p class="eyebrow">OPÉRATION HHT · 2026–2027</p><h1>Ventes & stock</h1><p class="muted">Connectez-vous pour retrouver le stock et enregistrer vos ventes.</p><form id="login-form"><label class="field">Adresse e-mail<input type="email" name="email" autocomplete="username" inputmode="email" required placeholder="vous@exemple.com"></label><label class="field">Mot de passe<input type="password" name="password" autocomplete="current-password" required></label><p class="error" role="alert">${escape(message)}</p><button class="primary full" type="submit">Se connecter</button></form><p class="small muted" style="margin:22px 0 0">Accès réservé à l’équipe Kolilink. Vos identifiants sont fournis par l’administrateur.</p></section>`;
}
async function poll(){
 clearTimeout(pollTimer);if(!profile)return;
 if(!document.hidden&&!busy&&!refreshBusy){refreshBusy=true;try{
  await refreshData();
  const typing=['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName);
  if(!dialog.open&&!typing&&!selected)render();else if(selected&&!typing)updateReceipt();
 }catch(error){
  storageError=true;renderStatus();
  if(error.code==='42501'||error.status===401){profile=null;state=emptyState();dialog.close();showLogin('Votre accès doit être vérifié. Reconnectez-vous ou contactez l’administrateur.');}
 }finally{refreshBusy=false;}}
 if(profile)pollTimer=setTimeout(poll,5000);
}
async function boot(){try{const snapshot=await backend.restoreSession();if(!snapshot){showLogin();return;}applySnapshot(snapshot);state.events=(await backend.history()).map(eventFrom);hasOlder=state.events.length===100;render();void poll();}catch{profile=null;showLogin('Connexion indisponible. Vérifiez votre connexion Internet puis reconnectez-vous.');}}
document.addEventListener('submit',async event=>{
 if(event.target.id!=='login-form')return;event.preventDefault();const form=event.target,b=form.querySelector('button'),data=new FormData(form);b.disabled=true;b.textContent='Connexion…';
 try{const snapshot=await backend.signIn(String(data.get('email')),String(data.get('password')));form.reset();applySnapshot(snapshot);state.events=(await backend.history()).map(eventFrom);hasOlder=state.events.length===100;view='vente';render();void poll();}
 catch(error){form.querySelector('[role="alert"]').textContent=error.code==='42501'?'Ce compte ne dispose pas encore d’un accès HHT. Contactez l’administrateur.':error.message?.includes('Invalid login')?'Adresse e-mail ou mot de passe incorrect.':'Connexion impossible. Vérifiez vos identifiants et votre connexion Internet.';b.disabled=false;b.textContent='Se connecter';}
});
function openingForm(){if(profile.role!=='admin')return;dialog.dataset.kind='opening';showDialog(`<div class="dialog-head"><h2 id="dialog-title">Inventaire initial</h2><button class="close" data-action="close" aria-label="Fermer">×</button></div><p class="small muted">Saisissez le stock physiquement présent avant le premier mouvement. Les fournitures déjà contenues dans les kits prêts ne doivent pas être comptées dans le vrac.</p><form id="opening-form"><label class="field">Kit ou fourniture<select name="item"><optgroup label="Kits déjà prêts">${kits.map(k=>`<option value="kit:${k.id}">${k.name}</option>`).join('')}</optgroup><optgroup label="Fournitures en vrac">${articles.map(a=>`<option value="article:${a.id}">${a.name}</option>`).join('')}</optgroup></select></label><label class="field">Quantité constatée<input name="qty" type="number" inputmode="numeric" min="1" max="10000" required></label><label class="field">Référence de l’inventaire<input name="note" maxlength="500" required placeholder="Ex. Comptage dépôt du 28 septembre"></label><p role="alert" class="error"></p><button type="submit" class="primary full">Enregistrer le stock initial</button></form>`);}
document.addEventListener('submit',async event=>{
 if(event.target.id!=='opening-form')return;event.preventDefault();if(busy||profile?.role!=='admin')return;const form=event.target,data=new FormData(form),[type,id]=String(data.get('item')).split(':'),b=form.querySelector('button[type=submit]');busy=true;b.disabled=true;
 try{await commit({id:crypto.randomUUID(),type:type==='kit'?'opening_kit':'opening_article',[type==='kit'?'kitId':'articleId']:id,qty:Number(data.get('qty')),note:String(data.get('note')).trim()});dialog.close();render();toast('Inventaire initial enregistré.');}catch(error){form.querySelector('[role=alert]').textContent=error.message;b.disabled=false;}finally{busy=false;}
});

async function sell(){if(busy||!selected||lastSale)return;const scope=dialog.open?dialog:document.querySelector('.receipt');const q=Number(scope?.querySelector('#sale-qty')?.value??qty);const date=scope?.querySelector('#sale-date')?.value||saleDate;if(!date||date>today())return showError('Vérifiez la date de vente.');busy=true;updateReceipt();try{const e=await commit({id:saleToken,type:'sale',kitId:selected,qty:q,date});lastSale=e;render();updateReceipt();}catch(e){showError(e.message);}finally{busy=false;const b=$('[data-action="sell"]');if(b)b.disabled=storageError;}}
function showError(msg){const node=dialog.open?dialog.querySelector('[role="alert"]'):$('#sale-error');if(node)node.textContent=msg;else toast(msg);}
function renderStock(){const raw=stockTab==='articles'&&role==='depot';const filtered=articles.filter(a=>a.name.toLocaleLowerCase('fr').includes(stockSearch.toLocaleLowerCase('fr')));return heading('INVENTAIRE HHT','Le stock, en un coup d’œil.','Les kits prêts et les fournitures restantes sont comptés séparément.',role==='depot'?`<div class="action-row">${profile.role==='admin'?'<button class="secondary-btn" data-action="opening">Inventaire initial</button>':''}<button class="primary" data-action="receive">+ Réceptionner</button></div>`:'')+`<section class="panel"><div class="filters"><button class="filter ${!raw?'active':''}" data-stocktab="kits">Kits prêts à vendre</button>${role==='depot'?`<button class="filter ${raw?'active':''}" data-stocktab="articles">Fournitures en vrac</button>`:''}</div>${raw?`<div class="toolbar"><input class="search" id="stock-search" type="search" placeholder="Rechercher une fourniture…" aria-label="Rechercher une fourniture" value="${escape(stockSearch)}"><span class="small muted">${articles.filter(a=>a.threshold!==null&&state.raw[a.id]<=a.threshold).length} articles au seuil d’alerte</span></div><div id="article-list">${articleRows(filtered)}</div>`:`<div class="table-wrap"><table><thead><tr><th>Kit</th><th class="number">Prêts à vendre</th>${role==='depot'?'<th class="number">Assemblables en plus</th>':''}<th>État</th></tr></thead><tbody>${kits.map(k=>`<tr><td><strong>${k.name}</strong><small>${money(k.price)} GNF</small></td><td class="number"><strong>${state.ready[k.id]}</strong></td>${role==='depot'?`<td class="number">${capacity(state,k)}</td>`:''}<td><span class="badge ${state.ready[k.id]<5?'warning':''}">${state.ready[k.id]===0?'À préparer':state.ready[k.id]<5?'Stock faible':'Disponible'}</span></td></tr>`).join('')}</tbody></table></div>${role==='depot'?'<p class="small muted">Les capacités d’assemblage sont calculées séparément : elles utilisent les mêmes fournitures et ne s’additionnent pas.</p>':''}`}</section>`;}
function articleRows(list){return list.length?list.map(a=>`<div class="article-row"><div><p>${a.name}</p><small>Seuil d’alerte : ${a.threshold??'à définir'} · Unité : ${a.unit}</small></div><div class="article-count">${state.raw[a.id]}<small class="${a.threshold!==null&&state.raw[a.id]<=a.threshold?'error':''}">${a.threshold!==null&&state.raw[a.id]<=a.threshold?'À réapprovisionner':'Disponible'}</small></div></div>`).join(''):'<p class="empty-row">Aucune fourniture ne correspond à votre recherche.</p>';}
function receiveForm(){dialog.dataset.kind='receive';showDialog(`<div class="dialog-head"><h2 id="dialog-title">Réceptionner des fournitures</h2><button class="close" data-action="close" aria-label="Fermer">×</button></div><form id="receive-form"><label class="field">Fournisseur<select name="supplier"><option>Papeterie Bappaya</option></select></label><label class="field">Article<select name="article">${articles.map(a=>`<option value="${a.id}">${a.name} (${a.unit})</option>`).join('')}</select></label><label class="field">Quantité reçue, en unités de stock<input name="qty" type="number" inputmode="numeric" min="1" max="10000" step="1" required placeholder="Ex. 50"></label><p class="small muted">Pour un carton, indiquez son contenu total. Un paquet de crayons compte comme un paquet.</p><p role="alert" class="error"></p><button class="primary full" type="submit">Ajouter au stock</button></form>`);}
function renderPrep(){const k=kitById(prepKit),cap=capacity(state,k);const limiting=Object.entries(k.recipe).filter(([id,n])=>Math.floor(state.raw[id]/n)===cap).map(([id])=>articleById(id).name);return heading('ATELIER HHT','Préparer les prochains kits.','Les fournitures sortent du vrac et deviennent des kits prêts à vendre.')+`<div class="two-cols"><section class="panel"><h2>Que préparez-vous ?</h2><label class="field">Kit<select id="prep-kit">${kits.map(k=>`<option value="${k.id}" ${k.id===prepKit?'selected':''}>${k.name}</option>`).join('')}</select></label><label class="field">Nombre de kits<input id="prep-qty" type="number" inputmode="numeric" min="1" max="10000" value="${prepQty}"></label><div class="info-box"><strong>${cap} kits assemblables</strong><br>Article${limiting.length>1?'s':''} limitant${limiting.length>1?'s':''} : ${limiting.join(', ')}.</div><p class="small muted" style="margin-top:15px">Kits déjà prêts : ${state.ready[k.id]}. Cette préparation en ajoute ${prepQty}.</p><button class="primary full" data-action="assemble" ${prepQty>cap||storageError?'disabled':''}>${icon('assemble')} Confirmer la préparation</button>${prepQty>cap?'<p class="error">Il manque des fournitures. Réduisez la quantité ou préparez un réapprovisionnement.</p>':''}</section><section class="panel"><div class="panel-heading"><h2>Fournitures à utiliser</h2><small>Pour ${prepQty} kit(s)</small></div><ul class="requirements">${Object.entries(k.recipe).map(([id,n])=>`<li><span>${articleById(id).name}<small class="muted"> · ${articleById(id).unit}</small></span><strong class="${n*prepQty>state.raw[id]?'error':''}">${n*prepQty} / ${state.raw[id]}</strong></li>`).join('')}</ul><p class="small muted">Quantité nécessaire / stock disponible. Les recettes CP et Lycée intègrent vos corrections.</p></section></div>`;}
function renderBuy(){const rows=requirements(state,plan,packing).filter(r=>r.missing>0),totalKits=Object.values(plan).reduce((a,b)=>a+b,0);return heading('ACHATS HHT','Commander juste ce qu’il manque.','Fixez une préparation supplémentaire, pour un ou plusieurs niveaux.')+`<div class="two-cols"><section class="panel"><div class="panel-heading"><h2>Objectif de préparation</h2><small>Kits supplémentaires</small></div><div class="table-wrap"><table><tbody>${kits.map(k=>`<tr><td><strong>${k.name}</strong><small>${state.ready[k.id]} déjà prêts</small></td><td class="number"><input class="plan-input" data-plan="${k.id}" type="number" inputmode="numeric" min="0" max="10000" value="${plan[k.id]||0}" aria-label="Objectif ${k.name}"></td></tr>`).join('')}</tbody></table></div><p class="small muted">Les besoins des niveaux sont additionnés avant de déduire le stock en vrac. Les kits déjà préparés ne sont pas démontés.</p></section><section class="panel" id="buy-result"><p class="eyebrow">FOURNISSEUR</p><h2>Papeterie Bappaya</h2><p class="small muted">Achat à l’unité par défaut. Renseignez un multiple uniquement si un conditionnement complet est nécessaire.</p><div class="info-box"><strong>${totalKits} kits supplémentaires</strong><br>${rows.length} référence${rows.length>1?'s':''} à commander.</div><div class="purchase-result">${!totalKits?'<p class="empty-row">Indiquez les quantités à préparer pour calculer les manquants.</p>':!rows.length?'<p class="empty-row">Tout est disponible. Aucun achat nécessaire pour cet objectif.</p>':`<div class="table-wrap"><table class="purchase-table"><thead><tr><th>Article</th><th class="number">Manque</th><th class="number">Multiple d’achat</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${articleById(r.id).name}<small>Commande : ${r.order} ${articleById(r.id).unit}(s)${r.pack>1?` · ${r.order/r.pack} lot(s) de ${r.pack}`:''}<br>Surplus : ${r.surplus}</small></td><td class="number">${r.missing}</td><td class="number"><input class="plan-input" data-pack="${r.id}" aria-label="Multiple d’achat ${articleById(r.id).name}" type="number" inputmode="numeric" min="1" max="10000" value="${r.pack}"></td></tr>`).join('')}</tbody></table></div><button class="primary full" data-action="print-order" style="margin-top:20px">Imprimer / enregistrer en PDF</button><p class="small muted">Vérifiez le conditionnement avant de transmettre le bon au fournisseur.</p>`}</div></section></div>`;}
function renderHistory(){const events=role==='depot'?state.events:state.events.filter(e=>e.type==='sale'||e.type==='cancel');const labels={sale:'Vente',assemble:'Préparation',receive:'Réception',cancel:'Annulation',opening_article:'Inventaire initial',opening_kit:'Inventaire initial'};return heading('JOURNAL HHT','Chaque mouvement, au même endroit.','Retrouvez les ventes, préparations et réceptions enregistrées.')+`<section class="panel">${events.length?`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Mouvement</th><th>Détail</th><th class="number">Quantité</th><th class="number">Montant</th><th></th></tr></thead><tbody>${events.map(e=>`<tr><td>${formatDate(e.at)}<small>${escape(e.author)}</small></td><td><span class="badge ${e.type==='cancel'||canceled(e.id)?'warning':''}">${e.type==='sale'&&canceled(e.id)?'Vente annulée':labels[e.type]}</span></td><td>${e.articleId?articleById(e.articleId).name:kitById(e.kitId).name}${e.type==='receive'?'<small>Papeterie Bappaya</small>':''}${e.type==='sale'?`<small>Date de vente : ${e.date}</small>`:''}</td><td class="number">${e.qty}</td><td class="number">${e.amount!=null?money(e.amount)+' GNF':'—'}</td><td>${e.type==='sale'&&!canceled(e.id)?`<button class="text-btn" data-action="cancel-sale" data-id="${e.id}">Annuler</button>`:''}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-cart"><span class="empty-symbol">'+icon('history')+'</span><strong>Aucun mouvement enregistré</strong>Vos ventes, préparations et réceptions apparaîtront ici.</div>'}${hasOlder?'<button class="secondary-btn history-more" data-action="older">Voir les mouvements précédents</button>':''}</section>`;}
function cancelForm(id){const e=state.events.find(e=>e.id===id);if(!e||canceled(id))return toast('Cette vente est déjà annulée.');dialog.dataset.kind='cancel';showDialog(`<div class="dialog-head"><h2 id="dialog-title">Annuler cette vente ?</h2><button class="close" data-action="close" aria-label="Fermer">×</button></div><p>${e.qty} × ${kitById(e.kitId).name} · <strong>${money(e.amount)} GNF</strong></p><p class="small muted">Confirmez uniquement si les kits restent au dépôt ou ont été rendus complets. Ils seront remis en stock ; la vente restera dans l’historique.</p><p role="alert" class="error"></p><div class="action-row"><button class="secondary-btn" data-action="close">Garder la vente</button><button class="primary" data-action="confirm-cancel" data-id="${id}">Confirmer l’annulation</button></div>`);}
function printOrder(){const rows=requirements(state,plan,packing).filter(r=>r.missing>0);if(!rows.length)return;$('#print-area').innerHTML=`<header><img src="kolilink-logo.png" alt="Kolilink"><div><h1>KOLILINK SARL</h1><span>Opération HHT · 2026–2027</span></div></header><h2>Bon de commande — Papeterie Bappaya</h2><p>${new Intl.DateTimeFormat('fr-FR',{dateStyle:'long',timeZone:'Africa/Conakry'}).format(new Date())}</p><p class="print-note"><strong>PROJET DE COMMANDE — À VALIDER</strong><br>Calcul effectué à partir du stock disponible.</p><p>Préparation : ${kits.filter(k=>plan[k.id]>0).map(k=>`${plan[k.id]} × ${k.name}`).join(' ; ')}.</p><table><thead><tr><th>Article</th><th>Manquant</th><th>À commander</th><th>Conditionnement</th><th>Surplus</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${articleById(r.id).name}</td><td>${r.missing}</td><td>${r.order} ${articleById(r.id).unit}(s)</td><td>${r.pack===1?'À l’unité':`${r.order/r.pack} lot(s) de ${r.pack}`}</td><td>${r.surplus}</td></tr>`).join('')}</tbody></table><footer>RCCM : GN.TCC.2026.8.05476 · NIF : 549027519<br>kolilinkcommercial@gmail.com · +224 620 30 69 73 / 623 24 77 46<br>Conditionnements à confirmer avec le fournisseur.</footer>`;window.print();}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||b.disabled||!profile)return;try{
 if(b.dataset.action==='signout'){await backend.signOut();clearTimeout(pollTimer);profile=null;state=emptyState();dialog.close();showLogin();return;}
 if(b.dataset.action==='opening'){openingForm();return;}
 if(b.dataset.action==='older'){b.disabled=true;const page=await backend.history(state.events.at(-1)?.sequence);hasOlder=page.length===100;const seen=new Set(state.events.map(e=>e.id));state.events.push(...page.map(eventFrom).filter(e=>!seen.has(e.id)));render();return;}
 if(b.dataset.action==='retry'){b.disabled=true;const p=readPending();if(p){await commit({...p.action,id:p.id});selected=null;lastSale=null;toast('Mouvement confirmé.');render();}return;}

 if(b.dataset.view){view=b.dataset.view;if(role!=='depot'&&['preparation','achats'].includes(view))view='vente';selected=null;lastSale=null;render();window.scrollTo({top:0,behavior:'smooth'});}
 else if(b.dataset.kit)selectKit(b.dataset.kit);
 else if(b.dataset.filter){filter=b.dataset.filter;render();}
 else if(b.dataset.stocktab){stockTab=b.dataset.stocktab;render();}
 else if(b.dataset.action==='plus'||b.dataset.action==='minus'){qty=Math.max(1,Math.min(state.ready[selected],qty+(b.dataset.action==='plus'?1:-1)));updateReceipt();}
 else if(b.dataset.action==='sell')await sell();
 else if(b.dataset.action==='close')dialog.close();
 else if(b.dataset.action==='new-sale'){selected=null;lastSale=null;dialog.close();render();}
 else if(b.dataset.action==='receive')receiveForm();
 else if(b.dataset.action==='assemble'){if(role!=='depot')return;const k=kitById(prepKit);b.disabled=true;await commit({id:crypto.randomUUID(),type:'assemble',kitId:prepKit,qty:prepQty});toast(`${prepQty} kit(s) ${k.short} ajoutés au stock prêt à vendre.`);render();}
 else if(b.dataset.action==='cancel-sale')cancelForm(b.dataset.id);
 else if(b.dataset.action==='confirm-cancel'){b.disabled=true;await commit({id:crypto.randomUUID(),type:'cancel',saleId:b.dataset.id,kitsReturned:true});lastSale=null;selected=null;dialog.close();toast('Vente annulée. Les kits sont de nouveau disponibles.');render();}
 else if(b.dataset.action==='print-order')printOrder();
 }catch(err){showError(err.message);b.disabled=false;}});
document.addEventListener('change',e=>{const t=e.target;try{
 if(t.id==='sale-qty'){qty=Number(t.value);if(!Number.isSafeInteger(qty)||qty<1||qty>state.ready[selected]){qty=1;toast('Quantité ajustée : choisissez un nombre de kits disponibles.');}updateReceipt();}
 if(t.id==='sale-date'){if(!t.value||t.value>today())t.value=today();saleDate=t.value;updateReceipt();}
 if(t.id==='prep-kit'){prepKit=t.value;render();}
 if(t.id==='prep-qty'){const n=Number(t.value);if(!Number.isSafeInteger(n)||n<1||n>10000){t.value=prepQty;toast('Choisissez une quantité entière entre 1 et 10 000.');return;}prepQty=n;render();}
 if(t.dataset.plan){const n=Number(t.value);if(!Number.isSafeInteger(n)||n<0||n>10000){t.value=plan[t.dataset.plan]||0;toast('Choisissez une quantité entière entre 0 et 10 000.');return;}plan[t.dataset.plan]=n;render();}
 if(t.dataset.pack){const n=Number(t.value);if(!Number.isSafeInteger(n)||n<1||n>10000){t.value=packing[t.dataset.pack]||1;toast('Le multiple doit être un entier positif.');return;}packing[t.dataset.pack]=n;render();}
 }catch(err){toast(err.message);}});
document.addEventListener('input',e=>{const t=e.target;if(t.dataset.plan){const n=Number(t.value);if(Number.isSafeInteger(n)&&n>=0&&n<=10000){plan[t.dataset.plan]=n;const temp=document.createElement('div');temp.innerHTML=renderBuy();$('#buy-result').replaceWith(temp.querySelector('#buy-result'));}}if(t.dataset.pack){const n=Number(t.value);if(Number.isSafeInteger(n)&&n>=1&&n<=10000){packing[t.dataset.pack]=n;const r=requirements(state,plan,packing).find(r=>r.id===t.dataset.pack);if(r)t.closest('tr').querySelector('small').innerHTML='Commande : '+r.order+' '+articleById(r.id).unit+'(s)'+(r.pack>1?' · '+r.order/r.pack+' lot(s) de '+r.pack:'')+'<br>Surplus : '+r.surplus;}}if(t.id==='sale-qty'){const n=Number(t.value);if(Number.isSafeInteger(n)&&n>0&&n<=state.ready[selected]){qty=n;const total=t.closest('.receipt-inner,dialog').querySelector('#sale-total');if(total)total.innerHTML=money(kitById(selected).price*n)+' <small>GNF</small>';}}if(e.target.id==='stock-search'){stockSearch=e.target.value;$('#article-list').innerHTML=articleRows(articles.filter(a=>a.name.toLocaleLowerCase('fr').includes(stockSearch.toLocaleLowerCase('fr'))));}});
document.addEventListener('submit',async e=>{if(e.target.id!=='receive-form')return;e.preventDefault();if(role!=='depot'||busy)return;const form=e.target,data=new FormData(form),b=form.querySelector('button[type="submit"]');busy=true;b.disabled=true;try{const n=Number(data.get('qty'));await commit({id:crypto.randomUUID(),type:'receive',articleId:data.get('article'),qty:n,supplierId:'bappaya'});dialog.close();toast(`${n} unité(s) réceptionnée(s). Stock mis à jour.`);render();}catch(err){form.querySelector('[role="alert"]').textContent=err.message;b.disabled=false;}finally{busy=false;}});
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
void boot();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_hht_stock',title:'Lire le stock HHT',description:'Lit le dernier stock HHT synchronisé pour le compte connecté.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!profile)throw Error("Connexion requise.");if(input&&Object.keys(input).length)throw Error('Aucun paramètre attendu.');return kits.map(k=>({kit:k.name,ready:state.ready[k.id],assemblable:capacity(state,k)}));}})).catch(()=>{});Promise.resolve(document.modelContext.registerTool({name:'start_hht_sale',title:'Préparer une vente HHT',description:'Ouvre le récapitulatif pour un kit, sans enregistrer la vente. La validation reste à effectuer.',inputSchema:{type:'object',properties:{kitId:{type:'string',enum:kits.map(k=>k.id)}},required:['kitId'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!profile)throw Error("Connexion requise.");if(!input||Object.keys(input).some(k=>k!=='kitId')||!kitById(input.kitId))throw Error('Kit inconnu.');view='vente';selectKit(input.kitId);return {staged:true,kitId:input.kitId,quantity:1,saleRecorded:false};}})).catch(()=>{});}catch{}}
