export const permissionLabels={sell:'Enregistrer des ventes',cancel_own:'Annuler ses propres ventes',cancel_all:'Annuler les ventes de tous',receive:'Réceptionner les fournitures',assemble:'Préparer les kits',opening:'Saisir le stock initial',history_all:'Voir les mouvements de tous',audit_read:'Consulter la traçabilité complète'};
export const roleLabels={commercial:'Commercial',depot:'Dépôt',admin:'Administrateur'};
export function defaultPermissions(role){return Object.fromEntries(Object.keys(permissionLabels).map(k=>[k,role==='admin'||['sell','cancel_own'].includes(k)||(role==='depot'&&!['opening','audit_read'].includes(k))]));}
export const auditLabels={sale:'Vente enregistrée',cancel:'Vente annulée',receive:'Fournitures réceptionnées',assemble:'Kits préparés',opening_article:'Stock initial de fournitures',opening_kit:'Stock initial de kits',member_joined:'Membre ajouté',member_updated:'Autorisations ou nom modifiés',member_disabled:'Accès désactivé',member_enabled:'Accès réactivé',invitation_created:'Invitation créée',invitation_revoked:'Invitation annulée',invitation_accepted:'Invitation acceptée'};

export function createTeamUi({backend,supabase,getProfile,escape,toast,render,dialog,kitById,articleById,boot}){
 let team={members:[],invitations:[]},loaded=false,loadError='',audit=[],auditLoaded=false,auditMore=false,actors=[],filters={actor:'',action:'',from:'',to:''},pending=false,editMember=null,inviteRequest=null;
 const stamp=t=>new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium',timeStyle:'medium',timeZone:'Africa/Conakry'}).format(new Date(t));
 const safe=escape;
 const modal=html=>{dialog.dataset.kind='team';dialog.innerHTML=html;if(!dialog.open)dialog.showModal();};
 const head=title=>`<div class="dialog-head"><h2 id="dialog-title">${title}</h2><button class="close" data-action="close" aria-label="Fermer">×</button></div>`;
 const rpc=async(name,args)=>{const {data,error}=await supabase.rpc(name,args);if(error)throw error;return data;};
 const errorText=e=>e?.message||'Connexion interrompue. Actualisez puis vérifiez le résultat avant de réessayer.';
 async function loadTeam(){try{team=await rpc('hht_team');loaded=true;loadError='';}catch(e){team={members:[],invitations:[]};loaded=false;loadError=errorText(e);}render();}
 async function loadAudit(more=false){try{
   const page=await rpc('hht_audit_list',{p_before:more?audit.at(-1)?.sequence:null,p_actor:filters.actor||null,p_action:filters.action||null,p_from:filters.from||null,p_to:filters.to||null});
   const seen=new Set(more?audit.map(x=>x.sequence):[]);audit=more?[...audit,...page.filter(x=>!seen.has(x.sequence))]:page;auditMore=page.length===100;auditLoaded=true;loadError='';
   actors=await rpc('hht_audit_actors');
 }catch(e){audit=[];auditLoaded=false;loadError=errorText(e);}render();}
 function permissionsFields(role,perms){return `<div id="permissions-fields" class="permission-grid">${Object.entries(permissionLabels).map(([k,label])=>`<label><input type="checkbox" name="perm-${k}" ${role==='admin'||perms[k]?'checked':''} ${role==='admin'?'disabled':''}><span>${label}</span></label>`).join('')}</div><p class="small muted">${role==='admin'?'Un administrateur dispose de tous les droits et gère l’équipe.':'Chaque membre peut consulter les kits disponibles et ses propres mouvements.'}</p>`;}
 function memberForm(member=null){editMember=member;inviteRequest=crypto.randomUUID();const role=member?.role||'commercial';modal(head(member?'Autorisations du membre':'Inviter un membre')+`<form id="team-form"><label class="field">Nom du membre<input name="name" maxlength="100" required value="${safe(member?.display_name||'')}" autocomplete="name"></label>${member?`<p class="small muted">${safe(member.email)}</p>`:'<label class="field">Adresse e-mail<input type="email" name="email" maxlength="254" autocomplete="email" required></label>'}<label class="field">Profil<select name="role" id="team-role">${Object.entries(roleLabels).map(([k,v])=>`<option value="${k}" ${role===k?'selected':''}>${v}</option>`).join('')}</select></label><fieldset class="permissions"><legend>Autorisations</legend><div id="permission-container">${permissionsFields(role,member?.permissions||defaultPermissions(role))}</div></fieldset>${member?`<label class="access-check"><input type="checkbox" name="active" ${member.active?'checked':''}> Accès actif</label>`:'<p class="small muted">Un lien personnel sera créé, valable au maximum une heure. Partagez-le directement avec cette personne. Aucun e-mail n’est envoyé automatiquement.</p>'}<p class="error" role="alert"></p><button class="primary full" type="submit">${member?'Enregistrer les autorisations':'Créer le lien d’invitation'}</button></form>`);}
 function teamHtml(){return `<div class="page-heading"><div><p class="eyebrow">ADMINISTRATION HHT</p><h1>Votre équipe.</h1><p>Un compte par personne. Des accès adaptés à son travail.</p></div><button class="primary" data-team="invite">+ Inviter un membre</button></div>${loadError?`<p class="error" role="alert">${safe(loadError)}</p>`:''}<section class="panel"><div class="panel-heading"><h2>Membres ${loaded?'· '+team.members.length:''}</h2><button class="text-btn" data-team="refresh">Actualiser</button></div>${!loaded?'<p>Chargement de l’équipe…</p>':`<div class="member-list">${team.members.map(m=>`<article class="member-row"><span class="member-avatar">${safe(m.display_name.slice(0,1).toUpperCase())}</span><div class="member-info"><strong>${safe(m.display_name)}${m.user_id===getProfile()?.id?' · Vous':''}</strong><small>${safe(m.email)}</small><span class="badge ${m.active?'':'warning'}">${roleLabels[m.role]} · ${m.active?'Actif':'Désactivé'}</span></div>${m.user_id===getProfile()?.id?'<small class="muted">Votre compte</small>':`<button class="secondary-btn" data-team="edit" data-id="${m.user_id}">Gérer l’accès</button>`}</article>`).join('')}</div>`}</section><section class="panel team-invitations"><h2>Invitations en attente</h2>${team.invitations.length?team.invitations.map(i=>`<article class="member-row"><div class="member-info"><strong>${safe(i.display_name)}</strong><small>${safe(i.email)} · ${roleLabels[i.role]}</small><small>${new Date(i.expires_at)<new Date()?'Expirée':'Valable jusqu’au '+stamp(i.expires_at)}</small></div><div class="action-row"><button class="text-btn" data-team="reinvite" data-id="${i.id}">Nouveau lien</button><button class="text-btn danger" data-team="revoke" data-id="${i.id}">Annuler</button></div></article>`).join(''):'<p class="muted">Aucune invitation en attente.</p>'}</section>`;}
 function auditHtml(){return `<div class="page-heading"><div><p class="eyebrow">TRAÇABILITÉ HHT</p><h1>Qui a fait quoi ?</h1><p>Actions enregistrées par le serveur · heures de Conakry.</p></div></div><section class="panel"><form id="audit-filter" class="audit-filters"><label class="field">Membre<select name="actor"><option value="">Tous les membres</option>${actors.map(a=>`<option value="${a.actor}" ${filters.actor===a.actor?'selected':''}>${safe(a.name)}</option>`).join('')}</select></label><label class="field">Action<select name="action"><option value="">Toutes les actions</option>${Object.entries(auditLabels).map(([k,v])=>`<option value="${k}" ${filters.action===k?'selected':''}>${v}</option>`).join('')}</select></label><label class="field">Du<input type="date" name="from" value="${filters.from}"></label><label class="field">Au<input type="date" name="to" value="${filters.to}"></label><button class="secondary-btn" type="submit">Filtrer</button></form>${loadError?`<p class="error" role="alert">${safe(loadError)}</p>`:''}${!auditLoaded?'<p>Chargement du journal…</p>':audit.length?`<div class="audit-list">${audit.map(e=>`<article class="audit-row"><div><strong>${safe(e.actor_name)}</strong><small>${stamp(e.created_at)}</small></div><div><span class="badge">${auditLabels[e.action]||safe(e.action)}</span><p>${summary(e)}</p></div><button class="text-btn" data-team="detail" data-seq="${e.sequence}">Détails</button></article>`).join('')}</div>`:'<p class="empty-row">Aucune action pour ces filtres.</p>'}${auditMore?'<button class="secondary-btn history-more" data-team="audit-more">Voir les actions précédentes</button>':''}<p class="small muted audit-note">Les opérations et les changements d’accès restent conservés, même après la désactivation d’un membre. Ce journal ne recense pas les simples consultations ni les tentatives de connexion.</p></section>`;}
 function summary(e){const a=e.after_data||{},b=e.before_data||{};if(a.kit_id||a.article_id){const item=a.kit_id?kitById(a.kit_id)?.name:articleById(a.article_id)?.name;return `${a.quantity} × ${safe(item||a.kit_id||a.article_id)}${a.amount_gnf!=null?' · '+new Intl.NumberFormat('fr-FR').format(a.amount_gnf)+' GNF':''}`;}return safe(a.display_name||b.display_name||a.email||e.target);}
 function details(e){const a=e.after_data||{},b=e.before_data||{};let rows=[];
 if(a.permissions){for(const [key,label] of Object.entries(permissionLabels)){const before=b.role==='admin'||!!b.permissions?.[key],after=a.role==='admin'||!!a.permissions[key];if(!e.before_data||before!==after)rows.push(`<li><span>${label}</span><strong>${e.before_data?(before?'Oui':'Non')+' → ':''}${after?'Oui':'Non'}</strong></li>`);}}
 const readable=v=>typeof v==='boolean'?(v?'Oui':'Non'):(roleLabels[v]??v);
 for(const [key,label] of [['display_name','Nom'],['email','Adresse e-mail'],['role','Profil'],['active','Accès actif']])if(key in a&&(!e.before_data||JSON.stringify(a[key])!==JSON.stringify(b[key])))rows.push(`<li><span>${label}</span><strong>${e.before_data?safe(readable(b[key]))+' → ':''}${safe(readable(a[key]))}</strong></li>`);
 if(a.swap_quantity)rows.push(`<li><span>Échange de cahiers depuis ${safe(kitById(a.swap_from)?.name||a.swap_from)}</span><strong>${a.swap_quantity} kit(s)</strong></li>`);
 if(Object.keys(a.ready_changes||{}).length){for(const [id,delta] of Object.entries(a.ready_changes))rows.push(`<li><span>Kits préparés · ${safe(kitById(id)?.name||id)}</span><strong>${delta>0?'+':''}${delta}</strong></li>`);}
 else if(a.ready_change)rows.push(`<li><span>Kits prêts</span><strong>${a.ready_change>0?'+':''}${a.ready_change}</strong></li>`);
 for(const [id,delta] of Object.entries(a.raw_changes||{}))rows.push(`<li><span>${safe(articleById(id)?.name||id)}</span><strong>${delta>0?'+':''}${delta}</strong></li>`);
 if(a.note)rows.push(`<li><span>Note</span><strong>${safe(a.note)}</strong></li>`);
 if(a.cancelled_sale_id)rows.push(`<li><span>Vente annulée</span><strong>${safe(a.cancelled_sale_id)}</strong></li>`);
 modal(head(auditLabels[e.action]||safe(e.action))+`<p><strong>${safe(e.actor_name)}</strong> · ${stamp(e.created_at)}</p><p>${summary(e)}</p><ul class="audit-details">${rows.join('')||'<li>Action enregistrée dans le journal.</li>'}</ul><p class="small muted audit-reference">Référence : ${safe(e.target)}<br>Auteur : ${safe(e.actor||'Administration Supabase')}<br>Événement n° ${e.sequence}</p>`);
 }
 async function invite(data){const {data:result,error}=await supabase.functions.invoke('hht-invite',{body:data});if(error){let message;try{message=(await error.context.json()).error;}catch{}throw Error(message||'Création du lien impossible. Vérifiez votre connexion.');}return result;}
 function linkModal(result){modal(head('Invitation prête')+`<p>Partagez ce lien uniquement avec le membre concerné. Il pourra activer son accès et choisir son mot de passe.</p><label class="field">Lien personnel<input id="invite-link" readonly value="${safe(result.url)}"></label><p class="small muted">Expire au plus tard le ${stamp(result.expiresAt)}. Aucun e-mail n’a été envoyé.</p><button class="primary full" data-team="copy">Copier le lien</button><p class="error" role="alert"></p>`);}
 document.addEventListener('change',e=>{if(e.target.id==='team-role'){const role=e.target.value;document.querySelector('#permission-container').innerHTML=permissionsFields(role,defaultPermissions(role));}});
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-team]');if(!b||b.disabled||pending||!getProfile())return;try{
   if(b.dataset.team==='invite')memberForm();
   else if(b.dataset.team==='edit')memberForm(team.members.find(m=>m.user_id===b.dataset.id));
   else if(b.dataset.team==='refresh')await loadTeam();
   else if(b.dataset.team==='detail')details(audit.find(a=>String(a.sequence)===b.dataset.seq));
   else if(b.dataset.team==='audit-more'){b.disabled=true;await loadAudit(true);}
   else if(b.dataset.team==='copy'){const input=document.querySelector('#invite-link');try{await navigator.clipboard.writeText(input.value);toast('Lien copié.');}catch{input.select();toast('Sélectionnez et copiez le lien.');}}
   else if(b.dataset.team==='reinvite'){const i=team.invitations.find(x=>x.id===b.dataset.id);editMember=null;memberForm();const form=document.querySelector('#team-form');form.elements.name.value=i.display_name;form.elements.email.value=i.email;form.elements.role.value=i.role;document.querySelector('#permission-container').innerHTML=permissionsFields(i.role,i.permissions);}
   else if(b.dataset.team==='revoke'){const i=team.invitations.find(x=>x.id===b.dataset.id);modal(head('Annuler cette invitation ?')+`<p>${safe(i.display_name)} ne pourra plus activer cet accès avec le lien envoyé.</p><button class="primary full" data-team="confirm-revoke" data-id="${i.id}">Annuler l’invitation</button><p class="error" role="alert"></p>`);}
   else if(b.dataset.team==='confirm-revoke'){pending=true;b.disabled=true;await rpc('hht_invite_revoke',{p_id:b.dataset.id});dialog.close();await loadTeam();toast('Invitation annulée.');}
 }catch(err){const errNode=dialog.open?dialog.querySelector('[role="alert"]'):null;if(errNode)errNode.textContent=errorText(err);else toast(errorText(err));b.disabled=false;}finally{pending=false;}});
 document.addEventListener('submit',async e=>{
   if(e.target.id==='audit-filter'){e.preventDefault();const f=new FormData(e.target);filters=Object.fromEntries(['actor','action','from','to'].map(k=>[k,String(f.get(k)||'')]));if(filters.from&&filters.to&&filters.from>filters.to){toast('La date de début doit précéder la date de fin.');return;}await loadAudit();return;}
   if(e.target.id!=='team-form')return;e.preventDefault();if(pending)return;pending=true;const form=e.target,button=form.querySelector('[type=submit]');button.disabled=true;
   try{const f=new FormData(form),role=String(f.get('role')),permissions=role==='admin'?defaultPermissions(role):Object.fromEntries(Object.keys(permissionLabels).map(k=>[k,f.has('perm-'+k)]));
     if(editMember){await rpc('hht_team_update',{p_user_id:editMember.user_id,p_name:String(f.get('name')).trim(),p_role:role,p_permissions:permissions,p_active:f.has('active'),p_expected:{name:editMember.display_name,role:editMember.role,permissions:editMember.permissions,active:editMember.active}});dialog.close();await loadTeam();toast('Autorisations enregistrées.');}
     else{const result=await invite({id:inviteRequest,email:String(f.get('email')).trim(),name:String(f.get('name')).trim(),role,permissions});await loadTeam();linkModal(result);}
   }catch(err){form.querySelector('[role="alert"]').textContent=errorText(err);button.disabled=false;}finally{pending=false;}
 });
 async function acceptInvitation(){const params=new URLSearchParams(location.hash.slice(1));if(!params.has('invite'))return false;
   const inviteId=params.get('invite'),hash=params.get('token_hash'),type=params.get('type'),existing=params.get('existing')==='true';history.replaceState(null,'',location.pathname+location.search);document.body.classList.add('signed-out');
   const main=document.querySelector('#main');if(!inviteId||!hash||!['invite','magiclink'].includes(type)){main.innerHTML='<section class="panel login-panel"><h1>Lien invalide</h1><p>Demandez un nouveau lien à votre administrateur.</p><a href="./">Retour à la connexion</a></section>';return true;}
   main.innerHTML=`<section class="panel login-panel"><img src="kolilink-logo.png" alt="Kolilink"><p class="eyebrow">BIENVENUE DANS L’ÉQUIPE HHT</p><h1>Activer mon accès</h1><p>${existing?'Ce lien vous permet de rejoindre HHT avec votre compte existant.':'Choisissez votre mot de passe personnel pour accéder aux ventes et au stock.'}</p><form id="accept-invite-form">${existing?'':'<label class="field">Votre mot de passe<input type="password" name="password" autocomplete="new-password" minlength="12" required></label><label class="field">Confirmer le mot de passe<input type="password" name="confirm" autocomplete="new-password" minlength="12" required></label><p class="small muted">Au moins 12 caractères.</p>'}<p role="alert" class="error"></p><button type="submit" class="primary full">Activer mon accès</button></form><p class="small muted"><a href="./">Retour à la connexion</a></p></section>`;
   let verified=false;document.querySelector('#accept-invite-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.target,button=form.querySelector('button'),f=new FormData(form);button.disabled=true;try{
     if(!existing&&(String(f.get('password')).length<12||f.get('password')!==f.get('confirm')))throw Error('Choisissez au moins 12 caractères et confirmez le même mot de passe.');
     if(!verified){await supabase.auth.signOut({scope:'local'});const {error}=await supabase.auth.verifyOtp({token_hash:hash,type});if(error)throw Error('Ce lien a expiré ou a déjà été utilisé. Demandez une nouvelle invitation.');verified=true;}
     if(!existing){const {error}=await supabase.auth.updateUser({password:String(f.get('password'))});if(error)throw Error('Le mot de passe a été refusé. Choisissez-en un autre.');}
     await rpc('hht_invite_claim',{p_id:inviteId});form.reset();await boot();
   }catch(err){form.querySelector('[role=alert]').textContent=errorText(err);button.disabled=false;}});return true;
 }
 return {teamHtml,auditHtml,loadTeam,loadAudit,acceptInvitation,clear(){team={members:[],invitations:[]};loaded=false;audit=[];auditLoaded=false;actors=[];}};
}
